# Generated by Django 3.1 on 2020-11-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Ảnh sản phẩm'),
        ),
    ]
