# Generated by Django 3.1 on 2020-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201115_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Xuất xứ'),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, max_length=10, verbose_name='Giới tính'),
        ),
    ]
