# Generated by Django 3.1 on 2020-11-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_origin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Purchase',
        ),
    ]
